### PR TITLE
WIP seeing if I can force multi platform builds 

### PR DESCRIPTION
**Pull request by AndrewAnnex**
despite noarch, might be easier to remove that instead

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AndrewAnnex** [comment]
@conda-forge-admin, please rerender

**Comment by AndrewAnnex** [comment]
@Juanlu001 this pr allows us to fully test the spiceypy feedstock, however it feels that the tests for the regression that caused https://github.com/AndrewAnnex/SpiceyPy/issues/305 really belongs in the cspice-feedstock repository. I do not know if there is a clean way of executing the spiceypy test suite within the cspice-feedstock repository however.

**Comment by Juanlu001** [comment]
> I do not know if there is a clean way of executing the spiceypy test suite within the cspice-feedstock repository however.

Hmmm I wonder the same thing... @conda-forge/core any advice?

**Comment by Juanlu001** [comment]
Oh, I see you are already trying it out in https://github.com/conda-forge/cspice-feedstock/pull/12/files#diff-e178b687b10a71a3348107ae3154e44cR36-R39.

**Comment by AndrewAnnex** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
You can use `test-downstreams` in `cspice-feedstock`. Using `requires` as in  https://github.com/conda-forge/cspice-feedstock/pull/12/files#diff-e178b687b10a71a3348107ae3154e44cR36-R39 creates a cycle, but `test-downstreams` will not.

**Comment by AndrewAnnex** [comment]
@isuruf thanks, I wish the conda-forge documentation detailed this (unless I just missed it) as it took a few minutes to find https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

**Pull request closed without merging**
